# Generated by Django 5.2.7 on 2025-11-02 05:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
        ('patients', '0002_alter_patient_email_alter_patient_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('movement_type', models.CharField(choices=[('flexion', 'Flexión'), ('extension', 'Extensión')], max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='foto')),
            ],
        ),
        migrations.CreateModel(
            name='PatientAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('angle', models.FloatField()),
                ('ai_observation', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.assessment')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
            ],
        ),
        migrations.DeleteModel(
            name='MotionAssessment',
        ),
    ]
