# Generated by Django 5.2.7 on 2025-11-02 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_assessment_patientassessment_delete_motionassessment'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='name',
            field=models.TextField(max_length=100, null=True, verbose_name='nombre'),
        ),
    ]
