# Generated by Django 5.2.7 on 2025-11-02 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_assessment_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='description',
            field=models.TextField(max_length=500, null=True, verbose_name='descripción'),
        ),
    ]
