# Generated by Django 5.2.7 on 2025-11-02 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0004_assessment_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='movement_type',
            field=models.CharField(choices=[('flexion', 'Flexión'), ('extension', 'Extensión'), ('flexo-extension', 'Flexo-Extensión')], max_length=20),
        ),
    ]
