# Generated by Django 5.2.7 on 2025-11-10 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0005_alter_assessment_movement_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='patientassessment',
            name='ai_observation',
        ),
        migrations.AddField(
            model_name='patientassessment',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='foto'),
        ),
    ]
