# Generated by Django 5.2.7 on 2025-11-10 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0006_remove_assessment_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='foto'),
        ),
    ]
