# Generated by Django 5.2.7 on 2025-11-10 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0007_assessment_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='photo',
        ),
    ]
