# Generated by Django 5.2.7 on 2025-11-11 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0008_remove_assessment_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientassessment',
            name='angle',
            field=models.IntegerField(),
        ),
    ]
