# Generated by Django 5.2.7 on 2025-11-01 20:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.TextField(max_length=100, verbose_name='Nombre Completo')),
                ('age', models.IntegerField()),
                ('sex', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=10, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('work', models.TextField(max_length=200, verbose_name='Trabajo')),
                ('medical_history', models.TextField(max_length=500, verbose_name='Antecedentes')),
                ('surgeries', models.TextField(blank=True, max_length=500, null=True, verbose_name='Cirugías')),
                ('pathologies', models.TextField(blank=True, max_length=500, null=True, verbose_name='Patologías')),
                ('medications', models.TextField(blank=True, max_length=500, null=True, verbose_name='Medicamentos')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
